/**
 * AgriNexus - Canonical Demo Accounts Registry (Backend)
 * 
 * Single Source of Truth for standard demonstration accounts.
 * Shared across database seeding (seed.js) and in-memory test/fallback stores (authMiddleware.js).
 */

const DEMO_USERS_CANONICAL = [
  // --- FARMERS ---
  {
    id: 'user_farmer_01',
    fullName: 'Ramesh Patel',
    phone: '9876543210',
    email: 'farmer@agrinexus.gov.in',
    role: 'FARMER',
    languagePreference: 'en',
    district: 'Lucknow',
    state: 'Uttar Pradesh',
    villageName: 'Chinhat',
    stateCode: 'UP',
    districtCode: 'UP_LUK',
    localityCode: 'UP_LUK_05',
    locationSource: 'REGISTERED',
    isActive: true,
    passwordPlain: 'password123'
  },
  {
    id: 'user_farmer_02',
    fullName: 'Rahul Sharma',
    phone: '9876543220',
    email: 'rahul.sharma@agrinexus.demo',
    role: 'FARMER',
    languagePreference: 'en',
    district: 'Lucknow',
    state: 'Uttar Pradesh',
    villageName: 'Malihabad',
    stateCode: 'UP',
    districtCode: 'UP_LUK',
    localityCode: 'UP_LUK_02',
    locationSource: 'REGISTERED',
    isActive: true,
    passwordPlain: 'password123'
  },
  {
    id: 'user_farmer_03',
    fullName: 'Priya Verma',
    phone: '9876543221',
    email: 'priya.verma@agrinexus.demo',
    role: 'FARMER',
    languagePreference: 'en',
    district: 'Lucknow',
    state: 'Uttar Pradesh',
    villageName: 'Bakshi Ka Talab',
    stateCode: 'UP',
    districtCode: 'UP_LUK',
    localityCode: 'UP_LUK_01',
    locationSource: 'REGISTERED',
    isActive: true,
    passwordPlain: 'password123'
  },
  {
    id: 'user_farmer_04',
    fullName: 'Amit Yadav',
    phone: '9876543202',
    email: 'amit.yadav@agrinexus.demo',
    role: 'FARMER',
    languagePreference: 'en',
    district: 'Lucknow',
    state: 'Uttar Pradesh',
    villageName: 'Mohan Road',
    stateCode: 'UP',
    districtCode: 'UP_LUK',
    localityCode: 'UP_LUK_11',
    locationSource: 'REGISTERED',
    isActive: true,
    passwordPlain: 'password123'
  },

  // --- PROCUREMENT CENTRE HEADS & OPERATING STAFF ---
  {
    id: 'user_staff_01',
    fullName: 'Satish Kumar',
    phone: '9876543211',
    email: 'gomtinagar.centre@agrinexus.demo',
    role: 'CENTRE_STAFF',
    centreCode: 'LKO_GOM01',
    assignedCentreId: 'c1',
    accountStatus: 'ACTIVE',
    designation: 'Centre Head',
    isCentreHead: true,
    languagePreference: 'en',
    district: 'Lucknow',
    state: 'Uttar Pradesh',
    stateCode: 'UP',
    districtCode: 'UP_LUK',
    isActive: true,
    passwordPlain: 'password123'
  },
  {
    id: 'user_staff_02',
    fullName: 'Sehore Mandi Procurement Manager',
    phone: '9876543218',
    email: 'sehore.centre@agrinexus.demo',
    role: 'CENTRE_STAFF',
    centreCode: 'SEH01',
    assignedCentreId: 'c1',
    accountStatus: 'ACTIVE',
    designation: 'Centre Head',
    isCentreHead: true,
    languagePreference: 'en',
    district: 'Sehore',
    state: 'Madhya Pradesh',
    stateCode: 'MP',
    districtCode: 'MP_SEH',
    isActive: true,
    passwordPlain: 'password123'
  },
  {
    id: 'user_staff_03',
    fullName: 'Kishan Seva Manager — Aliganj',
    phone: '9876543231',
    email: 'aliganj.centre@agrinexus.demo',
    role: 'CENTRE_STAFF',
    centreCode: 'LKO_ALI02',
    assignedCentreId: 'c2',
    accountStatus: 'ACTIVE',
    designation: 'Centre Head',
    isCentreHead: true,
    languagePreference: 'en',
    district: 'Lucknow',
    state: 'Uttar Pradesh',
    stateCode: 'UP',
    districtCode: 'UP_LUK',
    isActive: true,
    passwordPlain: 'password123'
  },
  {
    id: 'user_staff_04',
    fullName: 'Grain Mandi Incharge — Indira Nagar',
    phone: '9876543232',
    email: 'indiranagar.centre@agrinexus.demo',
    role: 'CENTRE_STAFF',
    centreCode: 'LKO_IND03',
    assignedCentreId: 'c3',
    accountStatus: 'ACTIVE',
    designation: 'Centre Head',
    isCentreHead: true,
    languagePreference: 'en',
    district: 'Lucknow',
    state: 'Uttar Pradesh',
    stateCode: 'UP',
    districtCode: 'UP_LUK',
    isActive: true,
    passwordPlain: 'password123'
  },
  {
    id: 'user_staff_05',
    fullName: 'APMC Officer — Alambagh',
    phone: '9876543233',
    email: 'alambagh.centre@agrinexus.demo',
    role: 'CENTRE_STAFF',
    centreCode: 'LKO_ALA05',
    assignedCentreId: 'c4',
    accountStatus: 'ACTIVE',
    designation: 'Centre Head',
    isCentreHead: true,
    languagePreference: 'en',
    district: 'Lucknow',
    state: 'Uttar Pradesh',
    stateCode: 'UP',
    districtCode: 'UP_LUK',
    isActive: true,
    passwordPlain: 'password123'
  },

  // Additional Centre Operational Staff (for rotation / assignment tests)
  {
    id: 'user_staff_op_01',
    fullName: 'Amit Sharma',
    phone: '9876543215',
    email: 'amit.sharma@agrinexus.demo',
    role: 'CENTRE_STAFF',
    centreCode: 'LKO_GOM01',
    assignedCentreId: 'c1',
    accountStatus: 'ACTIVE',
    designation: 'Procurement Officer',
    isCentreHead: false,
    languagePreference: 'en',
    district: 'Lucknow',
    state: 'Uttar Pradesh',
    stateCode: 'UP',
    districtCode: 'UP_LUK',
    isActive: true,
    passwordPlain: 'password123'
  },
  {
    id: 'user_staff_op_02',
    fullName: 'Pooja Verma',
    phone: '9876543216',
    email: 'pooja.verma@agrinexus.demo',
    role: 'CENTRE_STAFF',
    centreCode: 'LKO_GOM01',
    assignedCentreId: 'c1',
    accountStatus: 'ACTIVE',
    designation: 'Weighing Operator',
    isCentreHead: false,
    languagePreference: 'en',
    district: 'Lucknow',
    state: 'Uttar Pradesh',
    stateCode: 'UP',
    districtCode: 'UP_LUK',
    isActive: true,
    passwordPlain: 'password123'
  },
  {
    id: 'user_staff_op_03',
    fullName: 'Anil Verma',
    phone: '9876543217',
    email: 'anil.verma@agrinexus.demo',
    role: 'CENTRE_STAFF',
    centreCode: 'LKO_GOM01',
    assignedCentreId: 'c1',
    accountStatus: 'ACTIVE',
    designation: 'Quality Inspector',
    isCentreHead: false,
    languagePreference: 'en',
    district: 'Lucknow',
    state: 'Uttar Pradesh',
    stateCode: 'UP',
    districtCode: 'UP_LUK',
    isActive: true,
    passwordPlain: 'password123'
  },
  {
    id: 'user_staff_op_04',
    fullName: 'Ravi Sharma',
    phone: '9876543213',
    email: 'ravi.sharma@agrinexus.demo',
    role: 'CENTRE_STAFF',
    centreCode: 'LKO_GOM01',
    assignedCentreId: 'c1',
    accountStatus: 'ACTIVE',
    designation: 'Procurement Operator',
    isCentreHead: false,
    languagePreference: 'en',
    district: 'Lucknow',
    state: 'Uttar Pradesh',
    stateCode: 'UP',
    districtCode: 'UP_LUK',
    isActive: true,
    passwordPlain: 'password123'
  },

  // --- GOVERNMENT ADMINISTRATOR ---
  {
    id: 'user_admin_01',
    fullName: 'District Magistrate / Administrator',
    phone: '9876543212',
    email: 'admin@agrinexus.gov.in',
    role: 'ADMIN',
    languagePreference: 'en',
    district: 'Lucknow',
    state: 'Uttar Pradesh',
    stateCode: 'UP',
    districtCode: 'UP_LUK',
    isActive: true,
    passwordPlain: 'adminpassword'
  }
];

module.exports = {
  DEMO_USERS_CANONICAL
};
