/**
 * AgriNexus - Canonical Procurement Journey Lifecycle
 * 
 * Defines the unified state machine for all procurement transactions across
 * Farmer Portal, Procurement Centre Portal, and Administrator Portal.
 */

const PROCUREMENT_LIFECYCLE_STATES = {
  BOOKED: 'BOOKED',
  WAITING: 'WAITING',
  CALLED: 'CALLED',
  ARRIVED: 'ARRIVED',
  VERIFICATION: 'VERIFICATION',
  QUALITY_CHECK: 'QUALITY_CHECK',
  WEIGHING: 'WEIGHING',
  PROCUREMENT_CONFIRMED: 'PROCUREMENT_CONFIRMED',
  PAYMENT_PROCESSING: 'PAYMENT_PROCESSING',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
  REJECTED: 'REJECTED'
};

const ORDERED_LIFECYCLE_PIPELINE = [
  PROCUREMENT_LIFECYCLE_STATES.BOOKED,
  PROCUREMENT_LIFECYCLE_STATES.WAITING,
  PROCUREMENT_LIFECYCLE_STATES.CALLED,
  PROCUREMENT_LIFECYCLE_STATES.ARRIVED,
  PROCUREMENT_LIFECYCLE_STATES.VERIFICATION,
  PROCUREMENT_LIFECYCLE_STATES.QUALITY_CHECK,
  PROCUREMENT_LIFECYCLE_STATES.WEIGHING,
  PROCUREMENT_LIFECYCLE_STATES.PROCUREMENT_CONFIRMED,
  PROCUREMENT_LIFECYCLE_STATES.PAYMENT_PROCESSING,
  PROCUREMENT_LIFECYCLE_STATES.PAYMENT_COMPLETED
];

const TERMINAL_STATES = [
  PROCUREMENT_LIFECYCLE_STATES.PAYMENT_COMPLETED,
  PROCUREMENT_LIFECYCLE_STATES.CANCELLED,
  PROCUREMENT_LIFECYCLE_STATES.NO_SHOW,
  PROCUREMENT_LIFECYCLE_STATES.REJECTED
];

// Valid state transitions
const LIFECYCLE_TRANSITIONS = {
  BOOKED: ['WAITING', 'ARRIVED', 'CANCELLED', 'NO_SHOW'],
  WAITING: ['CALLED', 'CANCELLED', 'NO_SHOW'],
  CALLED: ['ARRIVED', 'NO_SHOW', 'CANCELLED'],
  ARRIVED: ['VERIFICATION', 'QUALITY_CHECK', 'CANCELLED'],
  VERIFICATION: ['QUALITY_CHECK', 'WEIGHING', 'REJECTED', 'CANCELLED'],
  QUALITY_CHECK: ['WEIGHING', 'REJECTED', 'CANCELLED'],
  WEIGHING: ['PROCUREMENT_CONFIRMED', 'REJECTED', 'CANCELLED'],
  PROCUREMENT_CONFIRMED: ['PAYMENT_PROCESSING', 'PAYMENT_COMPLETED', 'CANCELLED'],
  PAYMENT_PROCESSING: ['PAYMENT_COMPLETED', 'CANCELLED'],
  PAYMENT_COMPLETED: [],
  CANCELLED: [],
  NO_SHOW: [],
  REJECTED: []
};

/**
 * Normalizes legacy operational statuses to canonical lifecycle state
 */
const normalizeLifecycleState = (status) => {
  if (!status) return PROCUREMENT_LIFECYCLE_STATES.BOOKED;
  const upper = status.toString().trim().toUpperCase().replace(/[\s-]+/g, '_');

  const legacyMap = {
    'IN_QUEUE': PROCUREMENT_LIFECYCLE_STATES.WAITING,
    'QUEUE': PROCUREMENT_LIFECYCLE_STATES.WAITING,
    'QUALITY_CHECK': PROCUREMENT_LIFECYCLE_STATES.QUALITY_CHECK,
    'QUALITYCHECK': PROCUREMENT_LIFECYCLE_STATES.QUALITY_CHECK,
    'PROCUREMENT_COMPLETE': PROCUREMENT_LIFECYCLE_STATES.PROCUREMENT_CONFIRMED,
    'COMPLETED': PROCUREMENT_LIFECYCLE_STATES.PAYMENT_COMPLETED,
    'PAID': PROCUREMENT_LIFECYCLE_STATES.PAYMENT_COMPLETED,
    'SLOT_CONFIRMED': PROCUREMENT_LIFECYCLE_STATES.BOOKED,
    'PRODUCE_RECEIVED': PROCUREMENT_LIFECYCLE_STATES.ARRIVED,
    'QUALITY_VERIFIED': PROCUREMENT_LIFECYCLE_STATES.QUALITY_CHECK,
    'WEIGHED': PROCUREMENT_LIFECYCLE_STATES.WEIGHING
  };

  return legacyMap[upper] || upper;
};

const isTerminalState = (state) => {
  return TERMINAL_STATES.includes(state);
};

const canTransition = (currentState, targetState) => {
  const normalizedCurrent = normalizeLifecycleState(currentState);
  const normalizedTarget = normalizeLifecycleState(targetState);
  const allowed = LIFECYCLE_TRANSITIONS[normalizedCurrent] || [];
  return allowed.includes(normalizedTarget);
};

module.exports = {
  PROCUREMENT_LIFECYCLE_STATES,
  ORDERED_LIFECYCLE_PIPELINE,
  TERMINAL_STATES,
  LIFECYCLE_TRANSITIONS,
  normalizeLifecycleState,
  isTerminalState,
  canTransition
};
